name: Code Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint black isort mypy

      - name: Check code formatting with Black
        run: |
          black --check --diff .
        continue-on-error: true

      - name: Check import sorting with isort
        run: |
          isort --check-only --diff .
        continue-on-error: true

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv,venv,htmlcov || true
          # Exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.venv,venv,htmlcov || true

      - name: Lint with pylint
        run: |
          pylint *.py --exit-zero --ignore=.venv,venv,htmlcov || true

      - name: Type check with mypy
        run: |
          mypy . --ignore-missing-imports --no-strict-optional --exclude '\.venv|venv|htmlcov' || true

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit security check
        run: |
          bandit -r . -f json -o bandit-report.json --exclude .venv,venv,htmlcov || true

      - name: Check dependencies for vulnerabilities
        run: |
          safety check --json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: bandit-report.json
          retention-days: 30
