name: Quick CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quick-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run quick tests
        run: |
          pytest -v --tb=short -x

      - name: Check test coverage
        run: |
          pytest --cov=results_parser --cov=search_service --cov-report=term-missing --cov-fail-under=70
